root: true
env:
  es2021: true
  node: true
  browser: true
parser: '@babel/eslint-parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins: [html, svelte3]
extends:
  - xo
  - plugin:unicorn/recommended
overrides:
  -
    files: ['**/*.svelte']
    processor: 'svelte3/svelte3'
rules:
  indent: [error, tab]
  linebreak-style: [error, unix]
  quotes: [error, single]
  semi:  [error, never]
  semi-spacing:
    - error
    -
      before: false
      after: true
  no-console: off
  no-debugger: off
  # no-unused-expressions: off
  no-unused-expressions:
    - error
    -
      allowShortCircuit: true
      allowTernary: true
      allowTaggedTemplates: true
  camelcase: off
  capitalized-comments: off
  spaced-comment: off
  padding-line-between-statements: off
  no-undef-init: off
  unicorn/filename-case: off
  unicorn/prevent-abbreviations: off
  unicorn/no-reduce: off
  unicorn/no-array-reduce: off
  # unicorn/no-abusive-eslint-disable: off
  unicorn/prefer-includes: off
  unicorn/no-useless-undefined: off
  unicorn/no-zero-fractions: off
  unicorn/prefer-query-selector: off
  unicorn/import-style:
    - error
    -
      styles:
        util: false
        path:
          named: true
  no-multiple-empty-lines: 
    - error
    -
      max: 2
      maxBOF: 2
      maxEOF: 0
  # Bug no ctx.body Koa
  require-atomic-updates: off
