root: true
env:
  es2022: true
  node: true
  browser: true
parserOptions:
  ecmaVersion: 13
  sourceType: module
extends:
  - xo
  - plugin:unicorn/recommended
plugins:
  - svelte3
overrides:
  -
    files: ['**/*.svelte']
    processor: 'svelte3/svelte3'
rules:
  indent: [error, tab]
  linebreak-style: [error, unix]
  quotes: [error, single]
  semi:  [error, never]
  semi-spacing:
    - error
    -
      before: false
      after: true
  no-console: off
  no-debugger: off
  no-unused-expressions:
    - error
    -
      allowShortCircuit: true
      allowTernary: true
      allowTaggedTemplates: true
  camelcase: off
  capitalized-comments: off
  spaced-comment: off
  padding-line-between-statements: off
  no-undef-init: off
  no-multi-assign: off
  unicorn/filename-case: off
  unicorn/prevent-abbreviations: off
  unicorn/no-reduce: off
  unicorn/no-array-reduce: off
  unicorn/prefer-includes: off
  unicorn/no-useless-undefined: off
  unicorn/no-zero-fractions: off
  unicorn/prefer-query-selector: off
  # unicorn/prefer-object-from-entries: off
  # unicorn/no-null: off
  unicorn/import-style:
    - error
    -
      styles:
        util: false
        path:
          named: true
  # unicorn/no-abusive-eslint-disable: off
  # Bug no ctx.body Koa
  require-atomic-updates: off
  # Bug do svelte lint
  no-multiple-empty-lines:
    - error
    -
      max: 2
      maxBOF: 2
      maxEOF: 0
settings:
  svelte3/ignore-warnings:
    a11y-no-onchange: false
    a11y-label-has-associated-control: false
  svelte3/ignore-styles:
    attributes:
      postcss: false
      lang: false
